movieproject/movieapp/urls.py
from . import views
from django.urls import path

app_name = 'movieapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('movie/<int:movie_id>/', views.detail, name="detail"),
    path('add/', views.add_movie, name='add_movie'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete')
]

movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movieapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=250)
    dsc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name', 'dsc', 'year', 'img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Movie
from .forms import MovieForm


# Create your views here.
def index(request):
    movie = Movie.objects.all()
    context = {
        'movie_list': movie
    }
    return render(request, 'index.html', context)


def detail(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request, 'detail.html', {'movie': movie})


def add_movie(request):
    if request.method == 'POST':
        name = request.POST.get('name', )
        dsc = request.POST.get('dsc', )
        year = request.POST.get('year', )
        img = request.FILES['img']
        movie = Movie(name=name, dsc=dsc, year=year, img=img)
        movie.save()

    return render(request, 'add.html')


def update(request, id):
    movie = Movie.objects.get(id=id)
    form = MovieForm(request.POST or None, request.FILES, instance=movie)
    # form = MovieForm(instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'form': form, 'movie': movie})


def delete(request, id):
    if request.method == 'POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request, 'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}

<div class="container-fluid" style="margin-top:15px;">
    <form method="POST" enctype="multipart/form-data" style="width:70%">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" type="text" name="name" placeholder="Enter movie name" required><br>
        </div>
        <div class="form-group">
            <textarea class="form-control" name="dsc" rows="4" placeholder="Enter movie details"></textarea><br>
<!--            <input class="form-control" type="text" name="dsc" rows="4" placeholder="Enter movie details"><br>-->
        </div>
        <div class="form-group">
            <input class="form-control" type="text" name="year" placeholder="Enter movie year"><br>
        </div>
        <div class="form-group">
            <input class="form-control" type="file" name="img" required><br>
        </div>
        <input class="btn btn-warning" style="font-weight:600;" type="submit">
    </form>
</div>

{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Trirong">
    <link href="{% static 'style.css' %}" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'movieapp:index' %}">
      Online Movie Store
    </a>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
<form method="POST">
    {% csrf_token %}
    Are you sure want to delete this movie?
    <input type="submit">
</form>

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}

<div class="container-fluid" style="margin-top:15px;">
    <img src="{{movie.img.url}}" width="30%"><br><br>
    <h1 style="font-weight:600;">{{movie.name}}</h1><br>
    {{movie.dsc}}<br><br>
    Year: {{movie.year}}<br><br>
    <a style="font-weight:600;" class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">Update</a>
    <a style="font-weight:600;" class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
</div>

{% endblock %}

movieproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}

<div class="container-fluid" style="margin-top:15px;">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{form.as_p}}
        </div>
        <input class="btn btn-warning" style="font-weight:600;" type="submit">
    </form>
</div>

{% endblock %}

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container-fluid" style="margin-top:15px;">
    <!--    <h2>Movies</h2>-->
    <div style="display:flex;">
        {% for i in movie_list %}
        <div class="col-2" style="margin-right:15px;">
            <a href="{% url 'movieapp:detail' i.id %}" style="text-decoration: none;">
                <div class="movie_thumb">
                    <img src="{{i.img.url}}" width="100%">
                    <div class="movie_name">
                        <p style="font-weight:500; color:black;">{{i.name}}</p>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
    <a class="btn btn-warning" style="font-weight:600;" href="{% url 'movieapp:add_movie' %}">Add Movie</a>
</div>

{% endblock %}